@startuml
hide empty methods
hide empty attributes
hide circle
skinparam classAttributeIconSize 0
class mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 as "mssoc:civilengineering.dishwasher.energy_crisis.energy_policy.renewable.foodmanufacturing.homeappliances_17463923"
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : a sioc:Role
class mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances as "mssoc:civilengineering.dishwasher.energy_crisis.energy_policy.renewable.foodmanufacturing.homeappliances"
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 --> mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : sioc:has_scope
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : ms:has_pagerank 0.0206942
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : ms:has_reachability 386.05
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : ms:has_overall_influence 0.143948
class twitter_user_243236419 as "twitter_user:243236419"
twitter_user_243236419 : a sioc:UserAccount
class mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 as "mssoc:civilengineering.dishwasher.energy_crisis.energy_policy.renewable.foodmanufacturing.homeappliances_243236419"
twitter_user_243236419 --> mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : sioc:has_function
class twitter_user_17463923 as "twitter_user:17463923"
twitter_user_17463923 : a sioc:UserAccount
twitter_user_17463923 --> mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : sioc:has_function
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : a sioc:Role
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 --> mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : sioc:has_scope
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : ms:has_pagerank 0.020222
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : ms:has_reachability 434.15
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : ms:has_overall_influence 0.143038
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : a sioc:Forum
class twitter_ as "twitter:"
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances --> twitter_ : sioc:has_host
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:energy_crisis
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:dishwasher
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:civilengineering
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:foodmanufacturing
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:homeappliances
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:policy_energy
mssoc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:renewable
@enduml
